Do not raise same exception twice in fork_and_wait()
I used the following test:
  $ cat remote_tb.py
  from mkosi.run import fork_and_wait

  def f():
      g()

  def g():
      raise ValueError('one')

  def h():
      try:
          f()
      except ValueError as e:
          raise TypeError('two') from e

  fork_and_wait(h)

When this is executed, we print the following:
mkosi.run.RemoteException: Traceback (most recent call last):
  File "/home/zbyszek/src/mkosi/remote_tb.py", line 15, in <module>
      fork_and_wait(h)
    File "/home/zbyszek/src/mkosi/mkosi/run.py", line 166, in fork_and_wait
      result = target()
               ^^^^^^^^
    File "/home/zbyszek/src/mkosi/remote_tb.py", line 13, in h
      raise TypeError('two') from e
  TypeError: two

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/home/zbyszek/src/mkosi/remote_tb.py", line 15, in <module>
      fork_and_wait(h)
    File "/home/zbyszek/src/mkosi/mkosi/run.py", line 189, in fork_and_wait
      raise result.exception from result
  TypeError: two

Note that we say that 'TypeError: two' is the direct cause of 'TypeError: two'.
It seems that RemoteException already has provision of including the original
traceback.

With the patch:
  Traceback (most recent call last):
    File "/home/zbyszek/src/mkosi/remote_tb.py", line 15, in <module>
      fork_and_wait(h)
    File "/home/zbyszek/src/mkosi/mkosi/run.py", line 189, in fork_and_wait
      raise result
  mkosi.run.RemoteException: Traceback (most recent call last):
  File "/home/zbyszek/src/mkosi/remote_tb.py", line 15, in <module>
      fork_and_wait(h)
    File "/home/zbyszek/src/mkosi/mkosi/run.py", line 166, in fork_and_wait
      result = target()
               ^^^^^^^^
    File "/home/zbyszek/src/mkosi/remote_tb.py", line 13, in h
      raise TypeError('two') from e
  TypeError: two

(I think there's an indentation error. One "File" is not indented as expected.)

v2:
- also adjust the exception handling to suppress tb for MkosiError raised
  in remote process.

  Test case: bin/mkosi -d opensuse, which fails with
  'sh: line 1: exec: zypper: not found' (no traceback),
  and a countercase where ZeroDivisionError is raised (we get a traceback).