Sidestep privileged `btrfs subvolume delete` if Kernel 4.18+
These scary but mostly harmless errors appear when non-root runs
`mkosi build --debug`:
```
ERROR: Could not destroy subvolume/snapshot: Operation not permitted
WARNING: deletion failed with EPERM, you don't have permissions or send
may be in progress or the subvolume is set as default
```

The errors stem from `btrfs subvolume delete` requiring either running
as root, or the `user_subvol_rm_allowed` mount option.

Since kernel 4.18+ (2018), btrfs has allowed deletion of subvolumes
via the rmdir(2) syscall. So in practice, we almost always can just
use `rm -rf` to remove a subolume.

This patch sniffs `sysfs` for the btrfs `rmdir_subvol` feature and
if it's present, we don't have to special case the subvolume
delete and just use `rm`.

References:

From btrfs(5):

```
Historically, any user could create a snapshot even if he was
not owner of the source subvolume, the subvolume deletion has
been restricted for that reason. The subvolume creation has
been restricted but this mount option is still required.
This is a usability issue. Since 4.18, the rmdir(2) syscall
can delete an empty subvolume just like an ordinary directory.
Whether this is possible can be detected at runtime, see
rmdir_subvol feature in FILESYSTEM FEATURES.
```

Also from btrfs(5):
```
FILESYSTEM FEATURES

    - rmdir_subvol (since: 4.18)

    indicate that rmdir(2) syscall can delete an empty subvolume
    just like an ordinary directory. Note that this feature only
     depends on the kernel version.
```

From https://www.kernel.org/doc/html/v4.19/admin-guide/sysfs-rules.html:
```
- sysfs is always at /sys

    Parsing /proc/mounts is a waste of time. Other mount points are a system
    configuration bug you should not try to solve. For test cases, possibly
    support a SYSFS_PATH environment variable to overwrite the application’s
    behavior, but never try to search for sysfs.

```