Revert "Remove now-redundant check if partno is None"
This reverts commit 13052e658e95c5913bc11c9398faf24e60143d88.

luks_setup_all() depends on this function returning None in case
partno is None. Fixing it in the caller overly complicates it.
Let's fix the breakage and maybe later rework the code.

$ sudo mkosi -d fedora -r 29 -t raw_ext4 -b
...
subprocess.CalledProcessError: Command '['mkfs.ext4', '-L', 'home', '-M', '/home', '/dev/loop0pNone']' returned non-zero exit status 1.

To avoid the mistake again, annotate partno parameter as being
optional.