sandbox: handle case where dev node for tty doesn't exist better
In cec6ae1d ("sandbox: handle case where dev node for tty doesn't exist"),
code was added to try to deal with a device node not existing. For whatever
reason, a FileNotFoundError with errno=2 was raised back then, and I get
a more generic OSError with errno=19.

    $ python3 -c "import os; os.ttyname(2)"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
        import os; os.ttyname(2)
                   ~~~~~~~~~~^^^
    OSError: [Errno 19] No such device

Let's just handle both cases.