fix: explicitly fail on socket connection if connection is denied
When the user does have `systemd-nsresourced`, but the socket is unavailable for any reason (i.e. when the service is disabled/stopped), mkosi gets a `Connection refused` error and hangs instead of getting a varlink error.

<details>
<summary>Example logs</summary>
```
[~/opt/zirconium-dev/zirconium]$ ls /run/systemd/io.systemd.NamespaceResource -la
╭───┬───────────────────────────────────────────┬────────┬────────┬──────────┬───────────┬───────────┬───────┬──────┬───────┬──────┬────────────────┬────────────────┬────────────────╮
│ # │                   name                    │  type  │ target │ readonly │   mode    │ num_links │ inode │ user │ group │ size │    created     │    accessed    │    modified    │
├───┼───────────────────────────────────────────┼────────┼────────┼──────────┼───────────┼───────────┼───────┼──────┼───────┼──────┼────────────────┼────────────────┼────────────────┤
│ 0 │ /run/systemd/io.systemd.NamespaceResource │ socket │        │ false    │ rw-rw-rw- │         1 │  4869 │ root │ root  │  0 B │ 36 seconds ago │ 34 seconds ago │ 36 seconds ago │
╰───┴───────────────────────────────────────────┴────────┴────────┴──────────┴───────────┴───────────┴───────┴──────┴───────┴──────┴────────────────┴────────────────┴────────────────╯
[~/opt/zirconium-dev/zirconium]$ varlinkctl info /run/systemd/io.systemd.NamespaceResource
    Vendor: The systemd Project
   Product: systemd (systemd-nsresourcework)
   Version: 259.4 (259.4-1.fc44)
       URL: https://systemd.io/
Interfaces: io.systemd
            io.systemd.NamespaceResource
            io.systemd.UserDatabase
            org.varlink.service
[~/opt/zirconium-dev/zirconium]$ systemctl stop systemd-nsresourced.socket
[~/opt/zirconium-dev/zirconium]$ varlinkctl info /run/systemd/io.systemd.NamespaceResource
Failed to connect to '/run/systemd/io.systemd.NamespaceResource': Connection refused
[~/opt/zirconium-dev/zirconium]$ mkosi -B --debug
‣ Running bump script /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.bump
‣ + /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.bump
‣ 0.0s for step "Running bump script /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.bump"
‣ Bumping version: '20260313150552' → '20260313195044'
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.conf.d/avengemedia-danklinux.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.conf.d/niri-git.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.conf.d/norecommends.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.conf.d/subprojects.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.conf.d/terra.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.conf.d/theme.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.conf.d/ublue-os-packages.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.conf.d/zirconium-packages.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.profiles/base/mkosi.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.profiles/base/mkosi.conf.d/base-desktop.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.profiles/base/mkosi.conf.d/base-x86-64.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.profiles/bootc-ostree/mkosi.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.profiles/fedora-bootc-ostree/mkosi.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.profiles/fedora-bootc-ostree/mkosi.conf.d/bootloader-x64.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.profiles/fedora-bootc-ostree/mkosi.conf.d/bootloader.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.profiles/fedora-bootc-ostree/mkosi.conf.d/firmware.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.profiles/fedora-bootc-ostree/mkosi.conf.d/goodies.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.profiles/fedora-bootc-ostree/mkosi.conf.d/others.conf
‣ Loading configuration file /var/home/tulip/opt/zirconium-dev/zirconium/mkosi.profiles/fedora-bootc-ostree/mkosi.conf.d/rhel-edge.conf
‣ Loading configuration file /tmp/tmp1cv5z6ss/resources/mkosi-tools/mkosi.conf
‣ Loading configuration file /tmp/tmp1cv5z6ss/resources/mkosi-tools/mkosi.conf.d/azure-centos-fedora/mkosi.conf
‣ Loading configuration file /tmp/tmp1cv5z6ss/resources/mkosi-tools/mkosi.conf.d/azure-centos-fedora/mkosi.conf.d/efi.conf
‣ Loading configuration file /tmp/tmp1cv5z6ss/resources/mkosi-tools/mkosi.conf.d/azure-fedora/mkosi.conf
‣ Loading configuration file /tmp/tmp1cv5z6ss/resources/mkosi-tools/mkosi.conf.d/fedora/mkosi.conf
‣ Loading configuration file /tmp/tmp1cv5z6ss/resources/mkosi-tools/mkosi.profiles/misc/mkosi.conf
‣ Loading configuration file /tmp/tmp1cv5z6ss/resources/mkosi-tools/mkosi.profiles/misc/mkosi.conf.d/azure-centos-fedora.conf
‣ Loading configuration file /tmp/tmp1cv5z6ss/resources/mkosi-tools/mkosi.profiles/package-manager/mkosi.conf.d/fedora.conf
‣ Loading configuration file /tmp/tmp1cv5z6ss/resources/mkosi-tools/mkosi.profiles/runtime/mkosi.conf
‣ Loading configuration file /tmp/tmp1cv5z6ss/resources/mkosi-tools/mkosi.profiles/runtime/mkosi.conf.d/azure-centos-fedora/mkosi.conf
‣ Loading configuration file /tmp/tmp1cv5z6ss/resources/mkosi-tools/mkosi.profiles/runtime/mkosi.conf.d/azure-centos-fedora/mkosi.conf.d/edk2-ovmf.conf
‣ Loading configuration file /tmp/tmp1cv5z6ss/resources/mkosi-tools/mkosi.profiles/runtime/mkosi.conf.d/fedora.conf
‣ + tput cnorm
‣ + tput smam
Traceback (most recent call last):
  File "/var/home/tulip/opt/systemd/mkosi/mkosi/run.py", line 104, in uncaught_exception_handler
    yield
  File "/usr/lib64/python3.14/contextlib.py", line 85, in inner
    return func(*args, **kwds)
  File "/var/home/tulip/opt/systemd/mkosi/mkosi/__main__.py", line 44, in main
    run_verb(args, tools, images, resources=resources)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/tulip/opt/systemd/mkosi/mkosi/__init__.py", line 4989, in run_verb
    acquire_privileges(foreign=True, delegate=3)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/tulip/opt/systemd/mkosi/mkosi/sandbox.py", line 813, in acquire_privileges
    nsresource_allocate_user_range(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        userns_fd,
        ^^^^^^^^^^
    ...<3 lines>...
        become_root,
        ^^^^^^^^^^^^
    )
    ^
  File "/var/home/tulip/opt/systemd/mkosi/mkosi/sandbox.py", line 687, in nsresource_allocate_user_range
    varlink(
    ~~~~~~~^
        path="/run/systemd/io.systemd.NamespaceResource",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
        fds=(userns,),
        ^^^^^^^^^^^^^^
    )
    ^
  File "/var/home/tulip/opt/systemd/mkosi/mkosi/sandbox.py", line 637, in varlink
    sock.connect(os.fspath(path))
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 111] Connection refused
[~/opt/zirconium-dev/zirconium]$
```
</details>